### ISSUE TITLE
questions for Jasper on User Experience & Usability Requirements

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#129]
Ref: [User Experience & Usability Requirements](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2022#User_Experience_.26_Usability_Requirements)

> The goal of Easy Checks is prominently displayed and the starting point for visitors of the resource in such a way that it sets an accurate expectation.

Q: What is not clear or missing from the 2017 version? Are the first two sentences and the "scope" section not read (e.g., banner blindness)? Or the text itself not clear enough?

> The checks have easy to understand headings that indicate their relevancy for the visitor.

Q: What about the 2017 checks headings is not easy to understand? e.g., are the short ones too short?

> It offers a clear ‘route’ to guide visitors where to go and what to do.

Q: Is that something other than a list of checks?

> It allows visitors to easily skip this prescribed route and directly jump to specific checks.

Q: Is that other than a list of checks linked so users can pick whichever they want?

> It offers information one subject at a time with to-the-point text, so that it can be consumed in a small amount of time and the visitor does not get overwhelmed with information.

Q: Does "one subject at a time" = one check per web page?

**Comment by jasperjeurens** [comment]
> Ref: [User Experience & Usability Requirements](https://www.w3.org/WAI/EO

> > The goal of Easy Checks is prominently displayed and the starting point for visitors of the resource in such a way that it sets an accurate expectation.
> Q: What is not clear or missing from the 2017 version? Are the first two sentences and the "scope" section not read (e.g., banner blindness)? Or the text itself not clear enough?

Indeed, the scope ánd introduction video are easily missed and not being read. The first 2 sentences in black were missed in all cases. Banner blindness may play a role, and while the formatting of the white box is distinctive relative to the main body text, I think a 'table format' doesn't naturally imply 'introduction'. When I specifically steered users to read the contents, some of them mentioned an 'a-ha' moment where the purpose of the site seemed to 'click' (and which was in some cases different from their initial expectation).

> > The checks have easy to understand headings that indicate their relevancy for the visitor.
> Q: What about the 2017 checks headings is not easy to understand? e.g., are the short ones too short?

There's a couple of things going on here. Firstly, the headings are not easily indentify/find relative to the other headings and content on the page. Secondly, while concise, the heading names are quite generic and broad. They signal a topic, but not the related action. Since the checks are related to _doing_ something, the heading could reflect that: "check page titles" or "identify page titles" or "making page titles descriptive". --> this is where I go to do something with page titles.

> > It offers a clear ‘route’ to guide visitors where to go and what to do.
> Q: Is that something other than a list of checks?

A list of checks is a good start, But I feel the page could offer more guidance in some shape or form. For example: "follow these 4 steps to get a first review of your web content." or "this is where you start".

> > It allows visitors to easily skip this prescribed route and directly jump to specific checks.
> Q: Is that other than a list of checks linked so users can pick whichever they want?

No that seems right. It is the 'counter side' to the previous statement. While guidance can improve the user experience for some, users should have the freedom to freely browse/choose their own 'route' if they choose to do so.

> > It offers information one subject at a time with to-the-point text, so that it can be consumed in a small amount of time and the visitor does not get overwhelmed with information.
> Q: Does "one subject at a time" = one check per web page?

I think that would be logical design decision to meet this requirement, yeah. Another way to go could be something like cards, or some kind of carousel but I'd prefer to keep it more simple.

**Comment by shawna-slh** [comment]
Thanks for the additional info. Interesting.
