### ISSUE TITLE
Link checker

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-easy-checks#130]
I'm not sure if 'link checker' is a real thing? 
I think I originally suggested learning designer/instructional designer/educator, and how they're using easy checks to assess the accessibility of third party websites and content which they might use in learning. This is pretty standard practice, especially when it comes to distance/online education, and makes more sense to give it a specific context, other than 'link checker'.

**Comment by shawna-slh** [comment]
Hey Jade. "link checker" was meant to be a quick handle/category/summary in line with "employer", "mentor", "advocate",. The persona itself is "Li is providing a list of links for additional information [for a course lesson..."

I was trying to make it more broad than the learning environment since we already have a few in that area. (And I wanted another in the "Other" category haha)

And I'm not attached to it, so feel free to suggest rewrite!

**Comment by jade-mc** [comment]
Hi Shawn, 

Maybe it'd be easier to focus on the action within each context then so it's more flexible? 
That'd be easy to do in each category: 

Procurement, Employment screening, advocating, checking links. 

Jade
