### ISSUE TITLE
How many checks?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-easy-checks#140]
How many checks is too many?

Some other ideas around this...

One options is to group checks on the resource homepage. This would allow for more to be included without it seeming too overwhelming.

Grouping could be by theme or by difficulty.

**Comment by iadawn** [comment]
Just to flag a comment I made in the [EO meeting on 9th June](https://www.w3.org/2023/06/09-eo-minutes.html#item02); having a small number isn't necessarily the important thing. Ensuring that the overview page doesn't become overwhelming is the thing. This is where grouping will be useful.

**Comment by shawna-slh** [comment]
OK here's a pass at one idea.

### Really easy checks:
* Language
* Page title
* Orientation for mobile

### Core checks:
* Image text alternatives ("alt text") (pictures, illustrations, charts, etc.)
* Headings
* Text contrast ratio ("color contrast")
* Moving, Flashing, or Blinking Content
* Text spacing (or, maybe include with zoom since you’re looking for the same thing)

### Video and audio checks:
* Captions
* Transcripts
* Description
* Moving, Flashing, or Blinking Content

### Harder checks:
* Resize text, zoom, reflow
* Keyboard access and visual focus (maybe + focus not obscured)
* Form field labels

<hr>

_**Maybe add later:**_
* Focus not obscured OR maybe include as a check with keyboard access?

_**Not including in this iteration:**_
see [Easy Checks Prioritization](https://docs.google.com/spreadsheets/d/1FsKGXi1BrBHBId_ZwKLtloXBZL0GcouQ7c26r-XJLRw/edit?pli=1#gid=0)
* Link text – @@
* Links open new windows – it’s AAA
* Skip links - @@
* Lists
* Required fields
* Redundant color coding
* Readability
* Focus order
* Landmarks
* Error handling
* Tables
* Consistent help
* Non-text contrast
* Target size
* Accessible authentication
* Animation from interaction

**Comment by AndrewArch** [comment]
Shawn, I'm happy with your grouping & prioritisation for now. I would personally like to see readability added back in - could even be an easy check if [Hemingway](https://hemingwayapp.com/) is accessible

**Comment by iadawn** [comment]
Couple of things that I would argue about:

* Keeping each check as atomic as possible - for example, keyboard access and visible focus checks two different (albeit related items). Grouping them in the easy check makes it more involved to explain and unpack.
* Easy checks vs core checks - not sure on the terminology
* I would not include forms as a 'harder' check but as a specific group - they are too ubiquitous a barrier not to touch on with some degree of focus

**Comment by AndrewArch** [comment]
On reflection I'm wondering if we try and group the checks by what people will be checking, e.g.:
* Structure
* Navigation
* Multimedia
* Forms
* etc. 

We might end up with a miscellaneous group at the end, but I think this type of grouping would be better than Easy, Core, Harder mixed in with Multimedia and other information-type groupings

**Comment by shawna-slh** [comment]
***If*** all the checks can be made easy, then I fully support that idea.

My *big* concern is how often we've heard, "this is not easy" -- from users in hands-on WAI tour sessions to recent usability testing of the prototypes. (a few notes about that in https://github.com/w3c/wai-easy-checks/issues/84 )

My gut feeling is that we'll want to ease users in with some really easy checks first. And, we'll probably want to indicate some that might be harder, in respect for the audience.

And, I'm quite happy to be wrong -- that we craft all checks to be pretty easy to most audiences! :-)

(And even if we did re-title it, I think we still have the same [purpose](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2022#Purpose), [audiences](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2022#Target_Audience), [use cases](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2022#Use_Cases), etc.)
(note not to let this issue tangent into the title discussion - if we want to revisit that, it should be a new issue or discussion.)

**Comment by shawna-slh** [comment]
I also agree that we don't need to make final decisions on grouping for a while.

One idea for approach:
* Finish up quick drafts of the checks that we will probably include in the first iteration (but not spend much time on the ones we're not sure EOWG will want to include)
* Bring those to EOWG for [eagle review](https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Eagle_Review_.E2.80.94_Bird.27s-eye_view_.2F_30.2C000-feet) along with questions on potential grouping.

**Comment by iadawn** [comment]
Please move this to the dicussion #144
