### ISSUE TITLE
text edit - suggest removing note under "Forms, Labels, and Errors"

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-easy-checks#80]
“Note: This section is more complex than the others. If it's too complicated, consider skipping it for now and proceeding through the remaining checks.”

Suggest removing this note.  It seems contradictory.  Why are we including forms in easy checks?  Because they are vital to accessibility and something that web users deal with every day.

**Comment by slhenry** [comment]
Ah, yeah. The forms checks are borderline "easy" -- well, actually, they are *not* easy for some people.

fyi, here is the [Criteria for what to include as checks in Easy Checks](https://www.w3.org/WAI/EO/wiki/Eval_Analysis#Criteria_for_checks) We didn't include everything that is vital to accessibility, e.g., links, because they didn't meet the criteria.

We have found in training and informal usability testing that the forms section is indeed this is too hard for some Easy Checks users. After some debate, EOWG decided to include Forms, and add that note -- so people who could handle that section would, and people who couldn't handle that section would be OK skipping it, rather than get frustrated and potentially give up on the others.

We considered having a category of medium-easy checks, and putting the Forms there. :-) Perhaps we want to do something like that for the Next Generation of Easy Checks?

I propose leaving it as is for now, and considering it again for Next Gen.

@lakeen If you're OK with that, then we can leave this issue for later with my edits. If you want it to be considered more now -- through the Review Team &/or all of EOWG -- please change the Label from  "later version" to  "maybe pre-launch" (or let me know and I will :-). Thanks.

**Comment by yatil** [comment]
[totally post-launch, probably easy checks 2.0 material]

To be honest, I think most checks should be on their own pages, like
* Easy Check: Page Title
* Easy Check: Image Text Alternatives
* …
* Check: Forms, labels, and errors

That would make it easier to expand. I see that a lot of accessibility issues stem from developers or QA people not knowing how to look for accessibility. The easy checks are important, but it would be great if we could have simpler single pages for each topic. It would also allow us to add “super hard checks” for things that are hard to test, for example, keyboard traps.

**Comment by lakeen** [comment]
I don't agree that the note should stay as is.  I just think it send the wrong message for such a vital everyday function.  I know we have a lot of content to get through so I'll leave it marked as "later version"

@yatil - I agree that separating out the sections would help.

**Comment by sdeschamps-orange** [comment]
+1 with @lakeen : either it's on easy checks (or whatever its new name, "First checks" from what I saw on IRC minutes) or it isn't.  The notice could say that the item is a bit more tricky, but not that one could consider avoiding it, considering how critical it is and how well explained the checking procedure is. I looks feasible, although not as fast as other checks in the page.
+1 with @yatil : separate content.

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
